# Generated by Django 2.1.5 on 2022-02-10 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0002_auto_20220210_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,14}$')])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Medico')),
            ],
        ),
    ]
