TIPOS_SANGUINEOS = (("A+", "A+"),
("B+", "B+"),
("AB+", "AB+"),
("O+", "O+"),
("A-", "A-"),
("B-", "B-"),
("AB-", "AB-"),
("O-", "O-"))

ESPECIALIDADES_MEDICAS = (("Acupuntura", "Acupuntura"),
("Alergia e imunologia", "Alergia e imunologia"),
("Anestesiologia", "Anestesiologia"),
("Angiologia", "Angiologia"),
("Cardiologia", "Cardiologia"),
("Cirurgia cardiovascular", "Cirurgia cardiovascular"),
("Cirurgia da mão", "Cirurgia da mão"),
("Cirurgia de cabeça e pescoço", "Cirurgia de cabeça e pescoço"),
("Cirurgia do aparelho digestivo", "Cirurgia do aparelho digestivo"),
("Cirurgia geral", "Cirurgia geral"),
("Cirurgia oncológica", "Cirurgia oncológica"),
("Cirurgia pediátrica", "Cirurgia pediátrica"),
("Cirurgia plástica", "Cirurgia plástica"),
("Cirurgia torácica", "Cirurgia torácica"),
("Cirurgia vascular", "Cirurgia vascular"),
("Clínica médica", "Clínica médica"),
("Coloproctologia", "Coloproctologia"),
("Dermatologia", "Dermatologia"),
("Endocrinologia e metabologia", "Endocrinologia e metabologia"),
("Endoscopia", "Endoscopia"),
("Gastroenterologia", "Gastroenterologia"),
("Genética médica", "Genética médica"),
("Geriatria", "Geriatria"),
("Ginecologia e obstetrícia", "Ginecologia e obstetrícia"),
("Hematologia e hemoterapia", "Hematologia e hemoterapia"),
("Homeopatia", "Homeopatia"),
("Infectologia", "Infectologia"),
("Mastologia", "Mastologia"),
("Medicina de emergência", "Medicina de emergência"),
("Medicina de família e comunidade", "Medicina de família e comunidade"),
("Medicina do trabalho", "Medicina do trabalho"),
("Medicina de tráfego", "Medicina de tráfego"),
("Medicina esportiva", "Medicina esportiva"),
("Medicina física e reabilitação", "Medicina física e reabilitação"),
("Medicina intensiva", "Medicina intensiva"),
("Medicina legal e perícia médica", "Medicina legal e perícia médica"),
("Medicina nuclear", "Medicina nuclear"),
("Medicina preventiva e social", "Medicina preventiva e social"),
("Nefrologia", "Nefrologia"),
("Neurocirurgia", "Neurocirurgia"),
("Neurologia", "Neurologia"),
("Nutrologia", "Nutrologia"),
("Oftalmologia", "Oftalmologia"),
("Oncologia clínica", "Oncologia clínica"),
("Ortopedia e traumatologia", "Ortopedia e traumatologia"),
("Otorrinolaringologia", "Otorrinolaringologia"),
("Patologia", "Patologia"),
("Patologia clínica/medicina laboratorial", "Patologia clínica/medicina laboratorial"),
("Pediatria", "Pediatria"),
("Pneumologia", "Pneumologia"),
("Psiquiatria", "Psiquiatria"),
("Radiologia e diagnóstico por imagem", "Radiologia e diagnóstico por imagem"),
("Radioterapia", "Radioterapia"),
("Reumatologia", "Reumatologia"),
("Urologia", "Urologia"))